use_default_settings: true
general:
  instance_name: "TriForce Search"
search:
  safe_search: 0
  autocomplete: "google"
  default_lang: "de"
ui:
  default_theme: simple
  theme_args:
    simple_style: dark
